name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install cargo-php
      run: cargo install cargo-php --verbose

    - name: Run tests
      run: cargo test

    - name: Build ext
      run: cargo build --release

    - name: Run test.php with librust_php_js_min.so extension
      run: php -dextension=./target/release/librust_php_js_min.so -f test.php

